application:
  title: Wonder
  version: 1.0.0
  keycloak-url: ${KEYCLOAK_URL:http://localhost:8181/auth}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:wonder}
    username: ${DATABASE_USERNAME:super_user}
    password: ${DATABASE_PASSWORD:super_password}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:http://localhost:8181/auth/realms/wonder}
          jwk-set-uri: ${OAUTH2_JWK:http://localhost:8181/auth/realms/wonder/protocol/openid-connect/certs}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
jwt:
  auth:
    converter:
      resource-id: wonder
      principle-attribute: keycloak_id

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: 8080
  address: 0.0.0.0

